# Generated by Django 3.1.7 on 2021-05-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210514_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcompetitorsplayers',
            name='tournament_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcps', to='tournament.tournamentcompetitorsteams'),
        ),
    ]
