# Generated by Django 3.1.7 on 2021-04-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='cup',
            options={'verbose_name': 'Очник', 'verbose_name_plural': 'Очники'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='synchronous',
            options={'verbose_name': 'Синхрон', 'verbose_name_plural': 'Синхроны'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='tournamentbasemodel',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='tournamentcompetitorsplayers',
            options={'verbose_name': 'Игрок-участник', 'verbose_name_plural': 'Игроки-участники'},
        ),
        migrations.AlterModelOptions(
            name='tournamentcompetitorsteams',
            options={'verbose_name': 'Команда-участница', 'verbose_name_plural': 'Команды-участницы'},
        ),
    ]
