# Generated by Django 3.1.7 on 2021-04-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210423_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronous',
            name='question_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
