# Generated by Django 3.1.7 on 2021-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chgkuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
