# Generated by Django 3.1.7 on 2021-04-26 23:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210427_0332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chgkuser',
            managers=[
                ('objects', main.models.ChgkUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='chgkuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
