# Generated by Django 3.1.7 on 2021-05-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tournamentcompetitorsteams_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcompetitorsteams',
            name='alias_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
