# Generated by Django 3.1.7 on 2021-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cup_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbasemodel',
            name='questions_per_tour',
            field=models.JSONField(default={1: 12, 2: 12, 3: 12}),
            preserve_default=False,
        ),
    ]
